export const ROLE_ICONS: Record<string, string> = {
  'Aldeano':            '/roles/villager.png',
  'Lobo':               '/roles/werewolf.png',
  'Vidente':            '/roles/seer.png',
  'Hechicera':          '/roles/Witch.png',
  'Bruja':              '/roles/Witch.png',
  'Cazador':            '/roles/hunter.png',
  'Cupido':             '/roles/cupid.png',
  'Alcalde':            '/roles/Prince.png',
  'Guardián':           '/roles/Guardian.png',
  'Sacerdote':          '/roles/priest.png',
  'Niña':               '/roles/Sleeping Faerie.png',
  'Antiguo':            '/roles/Leper.png',
  'Profeta':            '/roles/Apprentice Seer.png',
  'Gemelas':            '/roles/twin.png',
  'Gemela':             '/roles/twin.png',
  'Hermanos':           '/roles/Watcher.png',
  'Médium':             '/roles/Ghost.png',
  'Juez':               '/roles/verdugo.png',
  'Oso':                '/roles/Shapeshifter.png',
  'Ladrón':             '/roles/Troublemaker.png',
  'Alquimista':         '/roles/Doctor.png',
  'Espía':              '/roles/Silencer.png',
  'Chivo Expiatorio':   '/roles/cursed.png',
  'Niño Salvaje':       '/roles/Drunken Man.png',
  'Ángel':              '/roles/angel resucitador.png',
  'Pícaro':             '/roles/River Siren.png',
  'Flautista':          '/roles/Enchantress.png',
  'Perro Lobo':         '/roles/lycanthrope.png',
  'Lobo Blanco':        '/roles/werewolf.png',
  // New roles
  'Alborotadora':       '/roles/Troublemaker.png',
  'Anciana Líder':      '/roles/Leader Crone.png',
  'Ángel Resucitador':  '/roles/angel resucitador.png',
  'Aprendiz de Vidente':'/roles/Apprentice Seer.png',
  'Doctor':             '/roles/Doctor.png',
  'Fantasma':           '/roles/Ghost.png',
  'Leprosa':            '/roles/Leper.png',
  'Licántropo':         '/roles/lycanthrope.png',
  'Príncipe':           '/roles/Prince.png',
  'Silenciadora':       '/roles/Silencer.png',
  'Sirena del Río':     '/roles/River Siren.png',
  'Vigía':              '/roles/Watcher.png',
  'Virginia Woolf':     '/roles/Virginia Woolf.png',
  'Cría de Lobo':       '/roles/wolf_cub.png',
  'Hada Buscadora':     '/roles/Seeker Faerie.png',
  'Maldito':            '/roles/cursed.png',
  'Banshee':            '/roles/Banshee.png',
  'Cambiaformas':       '/roles/Shapeshifter.png',
  'Hada Durmiente':     '/roles/Sleeping Faerie.png',
  'Hombre Ebrio':       '/roles/Drunken Man.png',
  'Líder del Culto':    '/roles/Cult Leader.png',
  'Pescador':           '/roles/Fisherman.png',
  'Vampiro':            '/roles/Vampire.png',
  'Verdugo':            '/roles/verdugo.png',
};

export function getRoleIcon(roleName: string): string {
  return ROLE_ICONS[roleName] ?? '/roles/villager.png';
}
