
export enum PlayerRoleEnum {
  villager = "villager",
  seer = "seer",
  doctor = "doctor",
  hunter = "hunter",
  guardian = "guardian",
  priest = "priest",
  prince = "prince",
  lycanthrope = "lycanthrope",
  twin = "twin",
  hechicera = "hechicera",
  ghost = "ghost",
  virginia_woolf = "virginia_woolf",
  leprosa = "leprosa",
  river_siren = "river_siren",
  lookout = "lookout",
  troublemaker = "troublemaker",
  silencer = "silencer",
  seer_apprentice = "seer_apprentice",
  elder_leader = "elder_leader",
  resurrector_angel = "resurrector_angel",
  werewolf = "werewolf",
  wolf_cub = "wolf_cub",
  cursed = "cursed",
  witch = "witch",
  seeker_fairy = "seeker_fairy",
  shapeshifter = "shapeshifter",
  drunk_man = "drunk_man",
  cult_leader = "cult_leader",
  fisherman = "fisherman",
  vampire = "vampire",
  banshee = "banshee",
  cupid = "cupid",
  executioner = "executioner",
  sleeping_fairy = "sleeping_fairy",
}
